<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/froala_editor.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/froala_style.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/code_view.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/draggable.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/colors.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/emoticons.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/image_manager.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/image.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/line_breaker.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/table.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/char_counter.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/video.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/fullscreen.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/file.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/quick_insert.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/help.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/third_party/spell_checker.css')}}">
<link rel="stylesheet" href="{{url('vendor/elsayednofal/froala-editor/css/plugins/special_characters.css')}}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.css">
